# Hydrogen

spacing         = 2
padding         = 0
hide_ascii      = true
separator       = ""
key_color       = "Red"
separator_color = "Yellow"

[palette]
type = "Dark"
visible = true
glyph = "󰧞 "

[bar]
glyph           = ""
symbol_open     = '['
symbol_close    = ']'
hide_delimiters = true
visible         = true

[box]
title           = ""
border          = "rounded"
visible         = true

[box.inner_margin]
x               = 1
y               = 0

[custom_ascii]
path = "~/.config/macchina/oni.txt"

[randomize]
key_color       = false
separator_color = false

[keys]
kernel          = "󰹢"
de              = "󰖲"
distro          = ""
terminal        = ""
shell           = ""
packages        = ""
uptime          = "󰥔"
memory          = ""
cpu             = "󰍛"
gpu             = "󰍹"
