# get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """$directory$character"""
right_format = """$all"""
palette = "catppuccin_mocha"

# insert blank line between shell prompts
add_newline = true

# replace prompt symbol
[character]
success_symbol = '[󰅂](bold mauve)'
error_symbol = "[󰅂](red)"
vimcmd_symbol = "[❮](green)"

[directory]
# truncation_length = 4
read_only = ' '
style = "surface2"

[cmd_duration]
format = '[ 󰥔]($style) [$duration]($style)'
style = 'yellow'

[golang]
format = '[$symbol($version)]($style)'
symbol = ' '

[git_branch]
format = '[$symbol$branch]($style)'
style = 'pink'

[git_status]
format = '( [](red)[$all_status [](red)]($style))'
style = 'fg:base bg:red'
# format = '( [\[$all_status$ahead_behind\]]($style))'
conflicted = ' '
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
up_to_date = ' '
untracked = ' '
stashed = ' '
modified = ' '
staged = '[++\($count\)](green)'
renamed = ' '
deleted = ' '

[package]
format = ' [$symbol$version]($style)'
symbol = "󰏗 "

[rust]
symbol = ' '
format = ' [$symbol]($style)[$version]($style)'

[lua]
format = ' [$symbol]($style)[$version](bold blue)'
symbol = ' '

[python]
format = ' [${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)'
symbol = ' '

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
